=== karanbalacoder/spring/webservices-xml/employees.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://info.kblogics"
	xmlns:tns="http://info.kblogics"
	elementFormDefault="qualified">

	<xsd:element name="employees" type="tns:employeesType"></xsd:element>

	<xsd:complexType name="employeesType">
		<xsd:sequence>
			<xsd:element name="employee" type="tns:employeeType" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="employeeType">
		<xsd:sequence>
			<xsd:element name="eno" type="xsd:int"></xsd:element>
			<xsd:element name="name" type="xsd:string"></xsd:element>
			<xsd:element name="salary" type="xsd:double"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== karanbalacoder/spring/webservices-xml/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<employees xmlns="http://info.kblogics"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://info.kblogics employees.xsd ">
	<employee>
		<eno>1</eno>
		<name>karan</name>
		<salary>10000</salary>
	</employee>
	
	<employee>
		<eno>2</eno>
		<name>bala</name>
		<salary>20000</salary>
	</employee>
	
	<employee>
		<eno>3</eno>
		<name>baba</name>
		<salary>30000</salary>
	</employee>

</employees>
